#' List LLM-callable scaffolder methods
#'
#' Returns the method names that an external reasoning system is allowed to
#' request through a machine-readable scaffolding message.
#'
#' @return Character vector of allowed method names.
#' @export
scaffolder_action_methods <- function() {
  c(
    "evaluate_task",
    "decompose_task",
    "ask_human_complete",
    "ask_human_changes",
    "ask_human_rule",
    "apply_human_feedback"
  )
}

#' Normalize candidate values
#'
#' @param x Candidate container.
#'
#' @return Character vector.
#' @keywords internal
.normalize_candidate_values <- function(x) {
  if (is.null(x)) {
    return(character())
  }
  unlist(x, use.names = FALSE)
}

#' Predict node ids generated by apply_human_feedback additions
#'
#' @param scaffolder A [`Scaffolder`] instance.
#' @param add Additions passed to `apply_human_feedback`.
#'
#' @return Character vector of predicted node ids.
#' @keywords internal
.predict_added_node_ids <- function(scaffolder, add) {
  if (is.null(add) || !length(add)) {
    return(character())
  }

  current_n <- nrow(scaffolder$workflow$nodes)
  vapply(seq_along(add), function(i) {
    item <- add[[i]]
    if (!is.null(item$id) && nzchar(as.character(item$id))) {
      as.character(item$id)
    } else {
      paste0("node_", current_n + i)
    }
  }, character(1))
}

#' Validate scaffolder action arguments for a specific method
#'
#' @param method Scaffolder method name.
#' @param args Named list of action arguments.
#'
#' @return Validated argument list, invisibly.
#' @keywords internal
.validate_scaffolder_action_args <- function(method, args) {
  if (is.null(args)) {
    args <- list()
  }
  if (!is.list(args)) {
    stop("Each action `args` field must be a list.", call. = FALSE)
  }

  known_args <- switch(
    method,
    evaluate_task = c("task"),
    decompose_task = c("task", "candidates"),
    ask_human_complete = c("node_id"),
    ask_human_changes = character(),
    ask_human_rule = c("node_id"),
    apply_human_feedback = c("completeness", "add", "remove", "rule_specs", "confidence"),
    stop("Unsupported scaffolder method: ", method, call. = FALSE)
  )

  extra_args <- setdiff(names(args), known_args)
  if (length(extra_args)) {
    stop(
      "Unsupported argument(s) for method `", method, "`: ",
      paste(extra_args, collapse = ", "),
      call. = FALSE
    )
  }

  if (identical(method, "evaluate_task")) {
    if (!is.character(args$task) || length(args$task) != 1L || !nzchar(args$task)) {
      stop("`evaluate_task` requires a non-empty `task` string.", call. = FALSE)
    }
  }

  if (identical(method, "decompose_task")) {
    if (!is.null(args$task) &&
        (!is.character(args$task) || length(args$task) != 1L || !nzchar(args$task))) {
      stop("`decompose_task.task` must be a non-empty string when provided.", call. = FALSE)
    }
    if (!is.null(args$candidates)) {
      if (!is.list(args$candidates) && !is.character(args$candidates)) {
        stop("`decompose_task.candidates` must be a character vector or list.", call. = FALSE)
      }
      candidate_values <- .normalize_candidate_values(args$candidates)
      if (!is.character(candidate_values) || !length(candidate_values) || any(!nzchar(candidate_values))) {
        stop("`decompose_task.candidates` must contain non-empty strings.", call. = FALSE)
      }
    }
  }

  if (method %in% c("ask_human_complete", "ask_human_rule")) {
    if (!is.character(args$node_id) || length(args$node_id) != 1L || !nzchar(args$node_id)) {
      stop("`", method, "` requires a non-empty `node_id` string.", call. = FALSE)
    }
  }

  if (identical(method, "ask_human_changes")) {
    if (length(args)) {
      stop("`ask_human_changes` does not accept arguments.", call. = FALSE)
    }
  }

  if (identical(method, "apply_human_feedback")) {
    if (!is.null(args$completeness) && !is.list(args$completeness)) {
      stop("`apply_human_feedback.completeness` must be a named list.", call. = FALSE)
    }
    if (!is.null(args$remove)) {
      remove_values <- unlist(args$remove, use.names = FALSE)
      if (!is.character(remove_values)) {
        stop("`apply_human_feedback.remove` must be character.", call. = FALSE)
      }
    }
    if (!is.null(args$rule_specs) && !is.list(args$rule_specs)) {
      stop("`apply_human_feedback.rule_specs` must be a named list.", call. = FALSE)
    }
    if (!is.null(args$confidence)) {
      if (!is.list(args$confidence)) {
        stop("`apply_human_feedback.confidence` must be a named list.", call. = FALSE)
      }
      confidence_values <- suppressWarnings(as.numeric(unlist(args$confidence, use.names = FALSE)))
      if (any(is.na(confidence_values)) || any(confidence_values < 0) || any(confidence_values > 1)) {
        stop("`apply_human_feedback.confidence` values must be numeric in [0, 1].", call. = FALSE)
      }
    }
    if (!is.null(args$add)) {
      if (!is.list(args$add)) {
        stop("`apply_human_feedback.add` must be a list of node records.", call. = FALSE)
      }
      for (item in args$add) {
        if (!is.list(item) || !is.character(item$label) || length(item$label) != 1L || !nzchar(item$label)) {
          stop("Each added node must include a non-empty `label`.", call. = FALSE)
        }
        if (!is.null(item$confidence)) {
          confidence_value <- suppressWarnings(as.numeric(item$confidence))
          if (length(confidence_value) != 1L || is.na(confidence_value) ||
              confidence_value < 0 || confidence_value > 1) {
            stop("Added node `confidence` must be numeric in [0, 1].", call. = FALSE)
          }
        }
      }
    }
  }

  invisible(args)
}

#' Validate scaffolder action references against current state
#'
#' @param scaffolder A [`Scaffolder`] instance.
#' @param method Scaffolder method name.
#' @param args Named list of action arguments.
#'
#' @return Invisibly returns `TRUE`.
#' @keywords internal
.validate_scaffolder_action_refs <- function(scaffolder, method, args) {
  if (is.null(args)) {
    return(invisible(TRUE))
  }

  existing_ids <- scaffolder$workflow$nodes$id

  if (method %in% c("ask_human_complete", "ask_human_rule")) {
    if (!(args$node_id %in% existing_ids)) {
      stop("Unknown workflow node reference: ", args$node_id, call. = FALSE)
    }
  }

  if (identical(method, "apply_human_feedback")) {
    added_ids <- .predict_added_node_ids(scaffolder, args$add)
    combined_ids <- unique(c(existing_ids, added_ids))

    if (length(added_ids) && any(duplicated(combined_ids))) {
      stop("Added node ids must be unique within the workflow.", call. = FALSE)
    }

    remove_ids <- if (is.null(args$remove)) character() else unlist(args$remove, use.names = FALSE)
    if (length(remove_ids) && any(!(remove_ids %in% combined_ids))) {
      stop("`apply_human_feedback.remove` contains unknown node ids.", call. = FALSE)
    }

    remaining_ids <- setdiff(combined_ids, remove_ids)
    ref_groups <- list(
      completeness = if (is.null(args$completeness)) character() else names(args$completeness),
      rule_specs = if (is.null(args$rule_specs)) character() else names(args$rule_specs),
      confidence = if (is.null(args$confidence)) character() else names(args$confidence)
    )

    for (group_name in names(ref_groups)) {
      refs <- ref_groups[[group_name]]
      if (length(refs) && any(!(refs %in% remaining_ids))) {
        stop(
          "`apply_human_feedback.", group_name,
          "` references unknown or removed node ids.",
          call. = FALSE
        )
      }
    }
  }

  invisible(TRUE)
}

#' Build an LLM prompt for scaffolding decisions
#'
#' Creates a prompt that describes the scaffolder's available methods, the task
#' context, the current workflow state, and the required machine-readable JSON
#' response format.
#'
#' @param scaffolder A [`Scaffolder`] instance.
#' @param task Optional task text. Defaults to the scaffolder's current task.
#' @param format Prompt payload format. Use `"json"` for SDK-facing structured
#'   payloads and `"markdown"` for prompts that a human may paste into a chat
#'   interface.
#'
#' @return Character string prompt.
#' @export
build_scaffolder_prompt <- function(scaffolder, task = NULL, format = "json") {
  stopifnot(inherits(scaffolder, "Scaffolder"))

  format <- match.arg(format, choices = c("json", "markdown"))
  task <- task %||% scaffolder$task

  workflow <- scaffolder$workflow_spec()
  workflow_payload <- list(
    task = workflow$task,
    nodes = workflow$nodes,
    edges = workflow$edges,
    metadata = workflow$metadata
  )

  action_schema <- list(
    actions = list(
      list(
        method = "decompose_task",
        args = list(
          candidates = list(
            "Clarify objectives",
            "Identify decision points"
          )
        )
      ),
      list(
        method = "ask_human_rule",
        args = list(node_id = "node_2")
      )
    ),
    notes = "Optional short reasoning note."
  )

  allowed_methods <- scaffolder_action_methods()
  workflow_json <- jsonlite::toJSON(
    workflow_payload,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null",
    na = "null"
  )
  schema_json <- jsonlite::toJSON(
    action_schema,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null",
    na = "null"
  )

  if (identical(format, "json")) {
    payload <- list(
      role = "scaffolding_reasoner",
      task = if (is.null(task)) "<unspecified>" else task,
      available_methods = allowed_methods,
      method_semantics = list(
        evaluate_task = "Register or refresh the active task.",
        decompose_task = "Propose workflow nodes for the task.",
        ask_human_complete = "Ask whether a node is complete.",
        ask_human_changes = "Ask whether nodes should be added or removed.",
        ask_human_rule = "Ask for a node-specific rule.",
        apply_human_feedback = "Apply structured workflow updates."
      ),
      decision_policy = c(
        "Prefer decompose_task when the task has not yet been broken into useful workflow nodes.",
        "Ask the human only when ambiguity, missing rules, or completion checks block progress.",
        "Do not ask the human for information that can be inferred directly from the task or current workflow.",
        "Use apply_human_feedback only for structured workflow updates, not for free-form reasoning.",
        "Never invent methods outside the allowed method list."
      ),
      current_workflow = workflow_payload,
      response_requirements = list(
        format = "json",
        rules = c(
          "Return machine-readable JSON only.",
          "Do not include markdown fences or prose outside JSON.",
          "The top-level object must contain `actions` and may contain `notes`.",
          "Each action must contain `method` and `args`."
        ),
        schema = action_schema
      )
    )

    return(jsonlite::toJSON(
      payload,
      auto_unbox = TRUE,
      pretty = TRUE,
      null = "null",
      na = "null"
    ))
  }

  paste(
    "# Scaffolding Reasoning Prompt",
    "",
    "You are assisting a scaffolding-oriented agent framework.",
    "Your job is to decide what scaffolding action should happen next.",
    "",
    "## Task",
    if (is.null(task)) "<unspecified>" else task,
    "",
    "## Available Scaffolder Methods",
    paste(paste0("- `", allowed_methods, "`"), collapse = "\n"),
    "",
    "## Method Semantics",
    "- `evaluate_task(task)`: register or refresh the active task.",
    "- `decompose_task(task, candidates)`: propose workflow nodes for the task.",
    "- `ask_human_complete(node_id)`: ask whether a node is complete.",
    "- `ask_human_changes()`: ask whether nodes should be added or removed.",
    "- `ask_human_rule(node_id)`: ask for a node-specific rule.",
    "- `apply_human_feedback(...)`: apply structured updates to the workflow.",
    "",
    "## Decision Policy",
    "- Prefer `decompose_task` when the task has not yet been broken into useful workflow nodes.",
    "- Ask the human only when ambiguity, missing rules, or completion checks block progress.",
    "- Do not ask the human for information that can be inferred directly from the task or current workflow.",
    "- Use `apply_human_feedback` only for structured workflow updates, not for free-form reasoning.",
    "- Never invent methods outside the allowed method list.",
    "",
    "## Current Workflow State",
    "```json",
    workflow_json,
    "```",
    "",
    "## Response Requirements",
    "- Respond with machine-readable JSON only.",
    "- Do not include markdown fences or explanatory prose outside JSON.",
    "- The JSON must have an `actions` array and may have a `notes` string.",
    "- Each action must contain `method` and `args`.",
    "",
    "## Expected JSON Shape",
    "```json",
    schema_json,
    "```",
    sep = "\n"
  )
}

#' Parse an LLM scaffolder message
#'
#' Parses a machine-readable scaffolder message from JSON into an R list.
#'
#' @param text Character string containing JSON.
#'
#' @return Parsed list.
#' @export
parse_scaffolder_message <- function(text) {
  if (!is.character(text) || length(text) != 1L || !nzchar(text)) {
    stop("`text` must be a non-empty JSON string.", call. = FALSE)
  }

  parsed <- tryCatch(
    jsonlite::fromJSON(text, simplifyVector = FALSE),
    error = function(e) {
      stop("Could not parse scaffolder message as JSON.", call. = FALSE)
    }
  )

  validate_scaffolder_message(parsed)
}

#' Validate a machine-readable scaffolder message
#'
#' @param x Parsed scaffolder message.
#' @param allowed_methods Character vector of allowed method names.
#'
#' @return The validated message, invisibly.
#' @export
validate_scaffolder_message <- function(
  x,
  allowed_methods = scaffolder_action_methods()
) {
  if (!is.list(x)) {
    stop("Scaffolder message must be a list.", call. = FALSE)
  }

    if (is.null(x$actions) || !is.list(x$actions)) {
    stop("Scaffolder message must contain an `actions` list.", call. = FALSE)
  }

  for (i in seq_along(x$actions)) {
    action <- x$actions[[i]]
    if (!is.list(action)) {
      stop("Each action must be a list.", call. = FALSE)
    }
    if (!is.character(action$method) || length(action$method) != 1L) {
      stop("Each action must contain a single `method` string.", call. = FALSE)
    }
    if (!(action$method %in% allowed_methods)) {
      stop("Unsupported scaffolder method: ", action$method, call. = FALSE)
    }
    if (is.null(action$args)) {
      action$args <- list()
      x$actions[[i]] <- action
    }
    if (!is.list(action$args)) {
      stop("Each action `args` field must be a list.", call. = FALSE)
    }
    .validate_scaffolder_action_args(action$method, action$args)
  }

  invisible(x)
}

#' Apply a machine-readable scaffolder message
#'
#' Parses and dispatches a machine-readable scaffolder message into concrete
#' calls on a [`Scaffolder`] instance.
#'
#' @param scaffolder A [`Scaffolder`] instance.
#' @param message Parsed message list or JSON string.
#' @param allowed_methods Character vector of allowed method names.
#' @param stop_on_error Whether to stop on the first action error. When `FALSE`,
#'   errors are collected in the returned result object.
#'
#' @return A standardized list with `applied_actions`, `workflow_after`,
#'   `human_prompts`, and `errors`.
#' @export
apply_scaffolder_message <- function(
  scaffolder,
  message,
  allowed_methods = scaffolder_action_methods(),
  stop_on_error = TRUE
) {
  stopifnot(inherits(scaffolder, "Scaffolder"))

  if (is.character(message)) {
    message <- parse_scaffolder_message(message)
  }
  validate_scaffolder_message(message, allowed_methods = allowed_methods)

  results <- vector("list", length(message$actions))
  human_prompts <- list()
  errors <- list()

  for (i in seq_along(message$actions)) {
    action <- message$actions[[i]]
    method <- action$method
    args <- action$args

    if (!is.function(scaffolder[[method]])) {
      stop("Scaffolder does not implement method: ", method, call. = FALSE)
    }

    execution <- tryCatch({
      .validate_scaffolder_action_refs(scaffolder, method, args)
      result <- do.call(scaffolder[[method]], args)
      list(ok = TRUE, result = result, error = NULL)
    }, error = function(e) {
      list(ok = FALSE, result = NULL, error = conditionMessage(e))
    })

    if (!execution$ok && isTRUE(stop_on_error)) {
      stop(execution$error, call. = FALSE)
    }

    results[[i]] <- list(
      index = i,
      method = method,
      args = args,
      status = if (execution$ok) "applied" else "error",
      result = execution$result,
      error = execution$error
    )

    if (execution$ok && method %in% c("ask_human_complete", "ask_human_changes", "ask_human_rule")) {
      human_prompts[[length(human_prompts) + 1]] <- list(
        index = i,
        method = method,
        prompt = execution$result
      )
    }
    if (!execution$ok) {
      errors[[length(errors) + 1]] <- list(
        index = i,
        method = method,
        error = execution$error
      )
    }
  }

  list(
    applied_actions = results,
    workflow_after = scaffolder$workflow_spec(),
    human_prompts = human_prompts,
    errors = errors
  )
}

#' Collect human-facing questions from scaffolding output
#'
#' Extracts pending human questions from a standardized dispatch result or, if no
#' dispatch result is supplied, from the scaffolder interaction log.
#'
#' @param scaffolder A [`Scaffolder`] instance.
#' @param dispatch_result Optional result object returned by
#'   [apply_scaffolder_message()].
#'
#' @return Data frame of human-facing prompts.
#' @export
collect_scaffolder_questions <- function(scaffolder, dispatch_result = NULL) {
  stopifnot(inherits(scaffolder, "Scaffolder"))

  if (!is.null(dispatch_result)) {
    prompts <- dispatch_result$human_prompts
    if (!length(prompts)) {
      return(data.frame(
        index = integer(),
        method = character(),
        node_id = character(),
        question = character(),
        stringsAsFactors = FALSE
      ))
    }

    return(do.call(rbind, lapply(prompts, function(item) {
      data.frame(
        index = item$index,
        method = item$method,
        node_id = item$prompt$node_id %||% NA_character_,
        question = item$prompt$question %||% NA_character_,
        stringsAsFactors = FALSE
      )
    })))
  }

  relevant_types <- c("ask_human_complete", "ask_human_changes", "ask_human_rule")
  log_items <- Filter(function(item) item$type %in% relevant_types, scaffolder$interaction_log)

  if (!length(log_items)) {
    return(data.frame(
      index = integer(),
      method = character(),
      node_id = character(),
      question = character(),
      stringsAsFactors = FALSE
    ))
  }

  do.call(rbind, lapply(seq_along(log_items), function(i) {
    item <- log_items[[i]]
    data.frame(
      index = i,
      method = item$type,
      node_id = item$payload$node_id %||% NA_character_,
      question = item$payload$question %||% NA_character_,
      stringsAsFactors = FALSE
    )
  }))
}
