#' Fetch a Time Series from FRED (Federal Reserve Economic Data)
#'
#' Downloads and parses a FRED time series using the specified API configuration.
#' The resulting data frame contains dates and numeric values. Missing or invalid values (".") are converted to \code{NA}.
#'
#' @param series_id A character string specifying the FRED series ID (e.g., \code{"GDP"}, \code{"CPIAUCSL"}).
#' @param config A list with FRED API details, typically generated by \code{tool_set_config("fred")}, containing:
#' \describe{
#'   \item{\code{api_key}}{Your FRED API key.}
#'   \item{\code{url}}{Base URL of the FRED API endpoint.}
#'   \item{\code{mode}}{File format, usually \code{"json"}.}
#' }
#'
#' @return A data frame with columns:
#' \describe{
#'   \item{\code{date}}{Date of the observation.}
#'   \item{\code{value}}{Numeric value (or \code{NA} if missing).}
#' }
#'
#' @examples
#' config <- tool_set_config("fred")
#' df <- fetch_fred_series("GDP", config)
#'
#' @export
fetch_fred_series <- function(series_id, config) {
  api_key <- config$api_key
  url <- config$url
  mode <- config$mode
  url <- sprintf("%s?series_id=%s&api_key=%s&file_type=%s", url, series_id, api_key, mode)
  data <- jsonlite::fromJSON(url)
  
  # contains "." in early GDP
  raw_values <- data$observations$value
  raw_values[raw_values == "."] <- NA
  numeric_values <- as.numeric(raw_values)
  
  df <- data.frame(
    date = as.Date(data$observations$date),
    value = numeric_values,
    stringsAsFactors = FALSE
  )
  return(df)
}


# agent <- NewsReaderAgent$new()
# agent$set_config('fred')
# agent$fetch_fred_series('GDP')